project:
  type: book

book:
  title: "Modul Praktikum Pemodelan Iklim"
  author: "Akhmad Faqih, Perdinan, Agung Baruna Setiawan Noor" 
  date: "2023"
  date-format: "YYYY"
  chapters:
    - index.qmd
    - praktikum-1.ipynb
    - praktikum-2.ipynb
    - praktikum-3.ipynb
    # - summary.qmd
bibliography: references.bib
crossref:
  chapters: true
  fig-prefix: Gambar # (default is "Figure")
  fig-title: Gambar
  tbl-prefix: Tabel # (default is "Table")
  tbl-title: Tabel
  eq-prefix: Persamaan
  eq-title: Persamaan
csl: ipb.csl
code-overflow: wrap
code-block-border-left: true
code-block-bg: "EFF5F5"

format:
#  html:
#    theme: cosmo
  pdf:
    colorlinks: true
    geometry:
      - top=20mm
      - left=20mm
      - right=20mm
      - bottom=30mm
      - heightrounded
    documentclass: scrbook
    papersize: letter
    toc-title: "Daftar Isi"
    cite-method: biblatex
    biblio-title: "Referensi"
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \usepackage{amsmath}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}

highlight-style: github